# Generated by Django 5.0.4 on 2024-04-27 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfichier', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fichier',
            new_name='UploadImage',
        ),
    ]
