# Generated by Django 5.0.4 on 2024-04-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfichier', '0002_rename_fichier_uploadimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='name',
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
