# Generated by Django 5.0.4 on 2024-04-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfichier', '0003_remove_uploadimage_name_alter_uploadimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='name',
            field=models.CharField(default='Untitled', max_length=200),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
